function genIdea() {
  var randNum = Math.floor(Math.random() * 350) + 1;
  document.getElementById('idea').innerHTML = ideas[randNum];
}

//ideas array
var ideas = ["Fitness Challenges/Dare App",
"Fun Workspaces Finder App", 
"Amazon Prime Now App Redesign",
"Stores POS App Concept",
"Charity/Non-Profit App – Freebie",
"Interior Design Social App",
"Curated Travel Stories App",
"Wifi Router – Management App",
"Yes Or No – App Concept",
"Groupon Mobile App Redesign",
"MyTrips – Shared Trip Planner App",
"ChatBots Analytics Mobile",
"Music Streaming App – Sketch Freebie",
"Yoga – Learning App Concept",
"LifeGoals – Long Term Goals App",
"Flight Tickets Deal Tracker App",
"Live Events Feedback – App Wireframe",
"ProductHunt Mobile App Redesign Concept",
"Dating App Sketch Freebie",
"Personal Health Tracker App",
"Staff Management App Wireframe",
"Discover Mobile App Redesign Concept",
"Minimal Calorie Count Tracker App",
"Live Trivia Game App Concept",
"UPS Mobile App Redesign Concept",
"Hand Picked Deals Finder Concept",
"Real Estate App Concept – Sketch Freebie",
"Startup Mentors/Founders Social App Concept",
"Daily Mood Diary App Concept",
"Blog Analytics Dashboard App",
"PartySwype – Tinder Style App",
"Day Planner App Wireframe",
"Dribbble Analytics App Concept",
"Diabetes – Sugar Tracker App",
"Mobile Login Pages Freebie",
"MySchool – Mobile App Wireframe",
"Influencer Rate Card App",
"Taxi Driver Dashboard App",
"Smart Fin-tech Investments App",
"Amazon Seller App Redesign",
"MyTrucker – Pitstops App",
"Pet Healthcare App Wireframe Concept",
"SaaS Product – Landing Page Freebie",
"Notifications Saver App Concept",
"Amazon Prime Video App Redesign",
"Live HashTag Performance Analytics App",
"WorkSpace Finder App Concept",
"Coupons and Discounts App – Sketch Freebie",
"Leads Management Dashboard iOS",
"Google Play Books App Redesign",
"Ad Management App Concept",
"Home Smart Security App",
"Dream Wishlist App",
"3PL Shipping App Wireframe",
"eBlocks – eCommerce Wireframing Kit – iOS",
"Hospital Finder App Wireframe",
"Students University App Concept",
"Hospital Management SaaS Concept",
"GroupMe App Redesign Concept",
"Minimal Fitness Tracker App",
"E-Mail Marketing Campaigns Dashboard",
"Savings Tracking App Concept",
"Family Safety App Wireframe",
"Google Play Movies App Redesign",
"My Credit Cards – App Concept",
"Mobile Onboarding Screens – Sketch Freebie",
"Mobile Charts & Analytics UI Kit v1.0",
"Google Trips Mobile App Redesign Concept",
"eCommerce Sales Tracking Dashboard",
"HashTag Generator iOS App Concept",
"Admin & Inventory Management App",
"CarPooling App Wireframe",
"Affiliate Income Dashboard Mobile",
"Car Parking Finder App Concept",
"Sales CRM Analytics – Dashboard App",
"VPN Mobile App UI Kit – Sketch Freebie",
"Sleep Tracker App Wireframe",
"Odd1Out – Fun Game Concept",
"BetterWishlist – Amazon Wishlist Price Tracker App",
"Social App UI Kit – Sketch Freebie",
"BMI Calculator App Concept",
"Google Play Music App Redesign Concept",
"Listies – Fun Vocabulary Based Game",
"YouTube Analytics Dashboard App",
"Audible.com App Redesign Concept",
"Minimal Budget Planner App",
"Nearby Events Explorer App Concept",
"Helpdesk Team Dashboard Mobile",
"Empty States – Mobile – Freebie",
"Meditation Assistant App Wireframe",
"JusDuIt – Motivational Challenges App",
"Tile Mobile App Redesign Concept",
"Minimal Expense Tracking App",
"Fuel Price Tracker App Concept",
"iQuit – Goals Motivator App Concept",
"Habit Tracker App Dashboard Concept",
"Coworking Space Booking App Wireframe",
"Restaurant Delivery Management System App",
"Personal Activity Tracker App Concept",
"Positivity Journal – App Concept",
"Buy/Sell – Marketplace App Freebie",
"Smart Apartment Finder App Concept",
"Venmo Mobile App Redesign Concept",
"Pizza Delivery App – Sketch Freebie",
"Invoice Generator App Concept – Wireframe",
"AR Clothing Detection App Concept",
"Google Photos App – Material 2.0 Redesign Concept",
"Minimal Project Management App Concept",
"eCommerce Revenue Dashboard Mobile",
"Anonymous Questions/Polls App – Wireframe",
"Kolorify – Color Palettes App Concept",
"Flight Booking App – Sketch Freebie",
"CommunityAsk – Local Recommendations App Concept",
"Telegram App Redesign Concept",
"Minimal App Onboarding Concept",
"Office – Workspace Dashboard App Concept",
"Minimal Fashion Store App – Free UI Kit",
"Instagram Analytics Dashboard App Concept",
"Bug Bounty – Community App – Wireframe",
"Investment Calculator Dashboard Concept",
"Travelogram – Minimal Travel Diary App",
"500px Mobile App Redesign Concept",
"Baby Development Tracker App Concept",
"Affiliate Income Dashboard Mobile",
"Split Bill & Financial Tracker App Concept",
"Woords – Fun Word Based Game Concept",
"CRM Product Landing Page Wireframe",
"Company Sales Performance Dashboard",
"Movie Booking App iOS – Sketch Freebie",
"Recipes App Landing Page Sketch Freebie",
"GoIbibo App Redesign Concept",
"Personal Portfolio Revisit – Minimal",
"Borrowing/Lending App Wireframe",
"Booking.com App Redesign Concept",
"Minimal Recipes App – Tinder Style",
"Gotcha! Trivia Questions Game",
"Vehicle Fuel & Service Record App",
"LastPass Mobile App Redesign",
"Design Agency Website Concept",
"Design Case Study Generator",
"SaaS Analytics Landing Page Freebie",
"Sales Performance Dashboard Concept",
"Parties & Events Finder App Concept",
"Money Saving Assistant – App",
"Running App Statistics Dashboard",
"ChatBot Landing Page Sketch Freebie",
"Investments App Exploration",
"Stock Trading Mobile App Dashboard",
"Project Management Mobile App",
"Portfolio Revamp Experiment",
"Mobile App Landing Page Sketch Freebie",
"Memories (Photos) App Concept",
"Time Tracker App Wireframe",
"Slack Mobile App Redesign Concept",
"Emergency Crisis Response App Concept",
"MacOS Finder Redesign Concept",
"RememberMe – Social Bookmarking App",
"Minimal Designer Portfolio – Dark Mode",
"Google Play Store Redesign – Material 2.0",
"Sales Cloud App – Dashboard",
"Social Media Influencer Dashboard",
"Web Hosting Landing Page Sketch Freebie",
"Minimal Designer Portfolio Website",
"App Landing Page Wireframe",
"Health History App Dashboard Concept",
"Design Challenges Creator App",
"SaaSify Landing Page Freebie",
"Artspiration Art Curation App",
"Yahoo Mail Mobile App Redesign Concept",
"eCommerce Warehouse Management – iPad App",
"Hostel/PG Finder App Wireframe",
"Suites & Lounge Management iPad App",
"Movies Streaming App Freebie",
"Podcast App Concept",
"Fuel Economy Tracker App Wireframe",
"Mutual Funds Investments App Dashboard",
"Travel Europe – Minimal Showcase",
"HDFC MobileBanking App – Redesign Concept",
"Garage Sales App Concept",
"Superbike Riding Dashboard Concept",
"Support Centre Mobile App Wireframe",
"AR City Discovery App Concept",
"ZARA Mobile App Redesign Concept",
"Fashion Website Landing Page",
"Bank Payment/Wallet App – Sketch Freebie",
"eCommerce Seller App Dashboard",
"Online Courses App Freebie",
"Project Management App – Tasks",
"Automate Phone Tasks App Concept",
"Glassdoor.com Mobile App Redesign",
"Home Services App Wireframe",
"Minimal Furniture Website Exploration",
"AR Travel Treasure Hunt App",
"OLX.in Mobile App Redesign Concept",
"MyHealth – Doctor App Wireframe",
"Food Delivery App – Sketch Freebie",
"xBucketList – AIO Bucket List App",
"Hotel Check-in App Dashboard",
"Travelistory – Travel Memories App",
"Fashion App Starter UI Kit – Freebie",
"eMail Marketing Dashboard Concept",
"iCalorie AR Dieting App Concept",
"Minimal Gym Lap Timer – App",
"Hotels & Tours App Wireframe Concept",
"Stuff.Do – Time Management App",
"Real Estate Landing Page Freebie",
"eCommerce Fashion Exploration",
"Customer Support Center Dashboard",
"Google Docs Redesign – Material 2.0",
"Dominos Mobile App Redesign Concept",
"Parking Finder App Wireframe",
"Wood Store – Minimal Website Exploration",
"Minimal Agency Website Concept",
"Recruitment HR App Dashboard",
"Recipe App Concept",
"iNews – iOS Starter UI Kit Freebie",
"ShotoniPhone Photography Website Concept",
"Library Book Locator App",
"Healthy Activities Tracker App",
"App Store Wireframe",
"Abstract Photography Concept",
"CamScanner App Redesign Concept",
"Organic Grocery Shopping App Wireframe",
"Crypto App – iOS UI Kit Freebie",
"Gmail App Redesign Concept – Material 2.0",
"Federal Tax Calculator App Concept",
"Minimal Quotes App Concept",
"Fitness App Dashboard – Mobile",
"iCab – Cab Booking App – Sketch Freebie",
"Product Designer Minimal Portfolio",
"DateVentures – Fun Dating App",
"Kanban Task Management Dashboard",
"YouTube App Redesign – Material Design 2.0",
"Credit Management Dashboard – Mobile App",
"CrimeAlerts – Navigation Safety App",
"Medicine Reminder/Tracker App",
"Kroduct – SaaS Product Landing – Sketch Freebie",
"TouchMeIfYouCan – Fun Mobile Game",
"RideBuddy – The Motorcyclists Roadtrips App",
"Google Assistant Redesign – Dark Mode",
"MakeGoogleDoIt – Minimal Homepage Concept",
"Truth or Dare Challenge – Game",
"StackExchange App Redesign Concept",
"Bike Tracking App Wireframe",
"MyPatients – Healthcare App for Doctors",
"FX Trading Dashboard",
"Zing: iOS UI Kit Sketch Freebie",
"Wedding Photography Site Exploration",
"Business Accounting Dashboard",
"AIO Travel Booking App Concept",
"FAQ Pages Sketch Freebie",
"Bike Rental App – White Space Challenge",
"College Library App Concept",
"mLife – Minimal Design Inspiration Blog",
"Edoption – Pet Adoption App Concept",
"School Management Dashboard – Sketch Freebie",
"NYTimes Website Redesign Concept",
"SitePing – Uptime Monitoring App",
"uTorrent Mac App Redesign Concept",
"esign News App – Funky Concept",
"Social Media Marketing – Dashboard",
"TriviaWars – Fun Quiz App Concept",
"LingSwap – Language App Wireframe",
"Zeteriors – Interiors Design App",
"Designer Portfolio Template – Freebie",
"Emoji Banking – Fun Mobile App Concept",
"Asset Management Tool Wireframe",
"iKnew – Minimal News App",
"Shipment Management Dashboard",
"Chrome Web Store – Redesign",
"Draw.io Challenge – Twitter App",
"iComm eCommerce Wireframe Kit Freebie",
"Smart Home IoT App",
"Recipes/Cooking App Wireframe",
"WordPress CMS Redesign Concept",
"Digital Agency – Minimal Concept",
"Office Assistant – Health Reminder App",
"Pixel Weather App",
"mCam – Minimal Camera App",
"HR Management – All In One App",
"Android Messages Redesign Concept",
"Help Center Homepage – Colorful Wireframe",
"Minimal Pricing Tables – Sketch Freebie",
"Minimal Analytics – Dashboard",
"Clean Web Analytics Dashboard",
"Minimal Web Headers – Sketch Freebie",
"MyPaleo – Diet Planner Dashboard – Wireframe",
"FunBank – Colourful Banking App",
"Boldie – Minimal Designer Portfolio",
"Adventure Travel App – Unlock.Life",
"YouTube Creator Studio iOS Dashboard",
"Unsplash.com Web Redesign Concept",
"Subscription Management App – FiftyShadesGrey Challenge",
"iBlocks – iOS Wireframe Kit – Sketch Freebie",
"RanDesigner – Design Brief Generator App",
"Minimal Fashion Website",
"Blockfolio Crypto App – Redesign Concept",
"Diet365 – Diet Planner App Concept",
"Restaurant – Waitress App – Dashboard",
"20 Creative 404 Error Pages – Sketch Freebie",
"Learning App – Wireframe Concept",
"ChatCharts – ChatBot Analytics Dashboard",
"Black & White Challenge – Portfolio",
"1x Dribbble Invite Giveaway",
"Food365 – Food Discovery & Delivery App",
"WhatsApp Redesign Concept",
"Sports App Concept – Wireframe",
"Google Keep Redesign Concept",
"Digital Agency Homepage – Sketch Freebie",
"DomainsDen – Minimal Website",
"No Black Challenge – Mobile Banking App",
"Wallpapers365 – Mobile App",
"365Web Analytics Dashboard",
"Green Challenge – Diet365",
"Login Screens iOS – Sketch Freebie",
"Real Estate App Wireframe",
"ZINGED eBike Homepage",
"Designer Resume Template – Sketch Freebie",
"Tisara Women Fashion App",
"Diet Planner App Wireframe",
"Dribbble Redesign Concept",
"ProDesk – Helpdesk Software Dashboard",
"Circla – Fun Game Concept",
"Trello Redesign Concept",
"Aqila Digital Agency",
"Quora.com Redesign",
"IPLT20 Auction Dashboard Concept",
"Trajan Pro Challenge – Wedding Agency",
"Designer365 Porfolio Sketch Freebie",
"IoT Fitness Tracker Dashboard",
"News365 – Card Based Daily News",
"PixelsCode High-Fidelity Wireframe",
"ElitePixels Personal Portfolio Freebie",
"RoadTrippin – Travel Mobile App",
"The Comic Sans MS Challenge",
"SpaceSquare Website Dashboard",
"Google Authenticator Redesign",
"Minimail – Minimal Email",
"Expense Tracker Dashboard",
"Infynyty – Sketch Plugin Idea",
"StockLove – Stock Image Mobile App",
"MusicBeats – No White Challenge",
"365Movies App",
"CryptoEx Wireframe",
"Minimal Host",
"ElitePixels Photography – Sketch Freebie",
"MyHosting Dashboard",
"Skype Redesign",
"Blog Template Sketch Freebie",
"Stock Trading App UX",
"The Papyrus Challenge",
"Exodus App Redesign",
"Minimal Portfolio",];


